#!/usr/bin/env bash
set -euo pipefail

# Build dependencies: autotools (autoconf, automake, autopoint, libtool),
# a C/C++ toolchain and make, pkg-config, gettext, gnome-common, curl,
# tar, python3, and development headers for GLib 2.0, IBus 1.0,
# Tkrzw and SQLite 3.

LIBPINYIN_TAG=2.11.91
LIBPINYIN_SHA=0c5e80e1200f84fab185d1c5bde458b770a0636c
IBUS_LIBPINYIN_TAG=1.16.5
IBUS_LIBPINYIN_SHA=2d2cdac0187101aa0cd7ac06694a8340721ddfbb

# Two archives publish each pinned commit, and they are DIFFERENT FILES with
# different checksums -- not mirrors of one byte stream:
#
#   * upstream's own `make dist` release tarball, served identically by
#     SourceForge (where debian/watch points) and by the Debian/Ubuntu
#     archive as the package's .orig.tar.gz -- measured byte-identical;
#   * GitHub's generated archive of the tag.
#
# Each therefore carries its own SHA-256, and each is checked against its
# own. The alternates are a source-availability measure, never a relaxation:
# an archive that matches none of the listed digests is refused, exactly as
# before.
#
# The dist tarball additionally bundles data/ -- all eighteen model20 export
# files, measured byte-identical to the pinned model20.text.tar.gz -- so the
# model extraction below lands on identical bytes rather than changing what
# the oracle is built from.
#
# Order is availability, not preference of provenance: the Debian/Ubuntu
# archive first because it is the best-mirrored of the three, SourceForge
# second (upstream's own host, but docs/findings/datagen-model20.md records
# it as flaky), GitHub last (the original pin source; its codeload endpoint
# is unreachable from some networks, including sandboxes that allow only
# anonymous git).
#
# Provenance is not taken on trust. Both dist tarballs carry a generated
# ChangeLog whose first line is `commit <sha>` naming the very commit pinned
# above, and a file-by-file comparison against a clone of that tag found
# 163 of 164 tracked files byte-identical -- the one difference being that
# ChangeLog, which is empty in git and generated by `make dist`. See
# docs/findings/oracle-provisioning.md.
LIBPINYIN_SOURCES=(
	"http://archive.ubuntu.com/ubuntu/pool/main/libp/libpinyin/libpinyin_$LIBPINYIN_TAG.orig.tar.gz ff3047b19d17b82e26891abbe1bb354a9da3f66393c07c71072de0615e21788c"
	"https://downloads.sourceforge.net/libpinyin/libpinyin-$LIBPINYIN_TAG.tar.gz ff3047b19d17b82e26891abbe1bb354a9da3f66393c07c71072de0615e21788c"
	"https://codeload.github.com/libpinyin/libpinyin/tar.gz/refs/tags/$LIBPINYIN_TAG eb25890dab0072eb0744c9ee1bc152051143b7bc23aea2a424792a9b1b84bdcb"
)
IBUS_LIBPINYIN_SOURCES=(
	"http://archive.ubuntu.com/ubuntu/pool/main/i/ibus-libpinyin/ibus-libpinyin_$IBUS_LIBPINYIN_TAG.orig.tar.gz cc652d48e68b8b03afc5e9e08509676aee89f9d492b9a3897cd028bcc800ce31"
	"https://downloads.sourceforge.net/libpinyin/ibus-libpinyin-$IBUS_LIBPINYIN_TAG.tar.gz cc652d48e68b8b03afc5e9e08509676aee89f9d492b9a3897cd028bcc800ce31"
	"https://codeload.github.com/libpinyin/ibus-libpinyin/tar.gz/refs/tags/$IBUS_LIBPINYIN_TAG ab6d6cc371e4ec0cda1471ef968e9545de69a404958ecfb4e68545ef4b328646"
)
MODEL_URL=https://downloads.sourceforge.net/libpinyin/models/model20.text.tar.gz
MODEL_SHA256=59c68e89d43ff85f5a309489499cbcde282d2b04bd91888734884b7defcb1155
# The pinned model20 export inventory (interpolation2.text + seventeen .table
# files). Keep in lockstep with tools/model/fetch-model.sh and
# crates/pinyin-oracle/src/model_cache.rs (EXPECTED_MODEL_FILES).
MODEL_FILES=(
	art.table
	culture.table
	economy.table
	gb_char.table
	gbk_char.table
	geology.table
	history.table
	interpolation2.text
	life.table
	merged.table
	nature.table
	opengram.table
	people.table
	punct.table
	science.table
	society.table
	sport.table
	technology.table
)
ORACLE_PIN_REF="libpinyin-$LIBPINYIN_TAG-$LIBPINYIN_SHA+model20-$MODEL_SHA256+dbm-tkrzw"

work_dir=${TMPDIR:-/tmp}/oxpinyin-oracle
prefix=
jobs=1
apply_patches_dir=
model_dir=

usage() {
	cat <<'EOF'
Usage: build-oracle.sh [OPTIONS]

Build the pinned libpinyin and ibus-libpinyin releases from verified archives.

Options:
  --work-dir DIR       Download and build directory (default: $TMPDIR/oxpinyin-oracle)
  --prefix DIR         Installation prefix (default: WORK_DIR/prefix)
  --jobs N             Parallel make jobs (default: 1)
  --apply-patches DIR  Apply every *.patch in DIR to libpinyin source before
                       autoreconf; each patch's SHA-256 is folded into pin_ref
                       and recorded in oracle-pin.txt so the patched build is
                       distinguishable from the unpatched pin. The install
                       prefix must also differ from the pinned build.
  --model-dir DIR      Use an already-extracted, SHA-verified model export (the
                       product of tools/model/fetch-model.sh) instead of
                       downloading the pinned archive. DIR must contain all
                       eighteen export files. Reusing a cache does not relax the
                       SHA-256 check: the archive that produced DIR was verified
                       against MODEL_SHA256 before extraction. Only the source
                       of the bytes changes, never whether they are checked.
  -h, --help           Show this help

Build variables CC, CXX, CFLAGS, CXXFLAGS and LDFLAGS are passed through.
The final stdout line is the absolute path to the built libpinyin shared object.
EOF
}

while (($#)); do
	case $1 in
	--work-dir)
		work_dir=$2
		shift 2
		;;
	--prefix)
		prefix=$2
		shift 2
		;;
	--jobs)
		jobs=$2
		shift 2
		;;
	--apply-patches)
		apply_patches_dir=$2
		shift 2
		;;
	--model-dir)
		model_dir=$2
		shift 2
		;;
	-h | --help)
		usage
		exit 0
		;;
	*)
		printf 'unknown option: %s\n' "$1" >&2
		usage >&2
		exit 2
		;;
	esac
done

if [[ -n $apply_patches_dir && -z $prefix ]]; then
	printf '%s
' '--apply-patches requires an explicit --prefix: a patched build must not land in the unpatched default prefix' >&2
	exit 2
fi

prefix=${prefix:-"$work_dir/prefix"}

case $jobs in
'' | *[!0-9]* | 0)
	printf '%s\n' '--jobs must be a positive integer' >&2
	exit 2
	;;
esac

for command in curl sha256sum tar autoreconf make pkg-config find sort xargs patch; do
	command -v "$command" >/dev/null 2>&1 || {
		printf 'required command not found: %s\n' "$command" >&2
		exit 1
	}
done

if [[ -e $prefix && ! -d $prefix ]]; then
	printf 'installation prefix is not a directory: %s\n' "$prefix" >&2
	exit 1
fi
if [[ -d $prefix && -n $(find "$prefix" -mindepth 1 -print -quit) ]]; then
	printf 'installation prefix must be empty: %s\n' "$prefix" >&2
	exit 1
fi

if [[ -n $model_dir ]]; then
	if [[ ! -d $model_dir ]]; then
		printf '%s\n' "--model-dir is not a directory: $model_dir" >&2
		exit 1
	fi
	missing=
	for f in "${MODEL_FILES[@]}"; do
		[[ -f "$model_dir/$f" ]] || missing="$missing $f"
	done
	if [[ -n $missing ]]; then
		printf 'FAIL: --model-dir is missing:%s\n' "$missing" >&2
		printf 'DIR must hold the verified model20 export (run tools/model/fetch-model.sh)\n' >&2
		exit 1
	fi
	# Require provenance: fetch-model.sh writes a marker recording the
	# SHA-256 of the archive that produced the extraction. Without it the
	# bytes could be any eighteen files with the right names. The marker
	# sits one level above the extracted dir (cache_dir/verified for
	# cache_dir/extracted/).
	marker=$model_dir/../verified
	if [[ ! -f $marker ]] || ! grep -qx "sha256=$MODEL_SHA256" "$marker"; then
		printf 'FAIL: --model-dir lacks a matching provenance marker\n' >&2
		printf '  expected sha256=%s in %s\n' "$MODEL_SHA256" "$marker" >&2
		printf '  run tools/model/fetch-model.sh to produce a verified cache\n' >&2
		exit 1
	fi
fi

mkdir -p "$work_dir/downloads" "$work_dir/src" "$prefix"
work_dir=$(cd "$work_dir" && pwd)
prefix=$(cd "$prefix" && pwd)

# Prefer the just-built libraries while retaining pkg-config's system defaults
# for declared build dependencies. Never inherit caller-provided search paths
# for those prefixes — EXCEPT a caller-supplied base such as
# PKG_CONFIG_PATH=/usr/local/lib/pkgconfig for a from-tarball libtkrzw:
# not every distro's pkg-config searches /usr/local by default, so dropping
# an inherited entry would break exactly that consumer.
export PKG_CONFIG_PATH="$prefix/lib/pkgconfig:$prefix/lib64/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}"
export LD_LIBRARY_PATH="$prefix/lib:$prefix/lib64"

# Downloads one archive and verifies it, from a single URL with a single
# expected digest. Used directly for the model, and by fetch_any below.
fetch() {
	local name=$1 url=$2 expected=$3 path=$work_dir/downloads/$1
	if [[ ! -f $path ]]; then
		curl --fail --location --retry 3 --show-error "$url" --output "$path"
	fi
	printf '%s  %s\n' "$expected" "$path" | sha256sum --check --status || {
		printf 'checksum mismatch: %s\n' "$name" >&2
		exit 1
	}
	printf '%s\n' "$path"
}

# Downloads the first reachable archive from a list of "URL SHA256" pairs,
# checking each against ITS OWN digest.
#
# The alternates exist because the same pinned commit is published as two
# different files (see the source lists above), and because one host being
# unreachable must not stop a developer building the pin. What they are NOT
# is a weakening of verification:
#
#   * every candidate is checked against the digest listed beside it, so an
#     archive nobody pinned cannot be substituted for one that was;
#   * a download that SUCCEEDS but fails its digest is fatal immediately --
#     it is a corrupted or substituted artifact, and moving on to the next
#     host would paper over exactly the thing the digest is for;
#   * only a download that never produced a file (unreachable host, HTTP
#     error, refused connection) advances to the next candidate;
#   * exhausting the list is fatal and names every URL tried.
fetch_any() {
	local name=$1
	shift
	local path=$work_dir/downloads/$name
	local -a tried=()
	local entry url expected

	for entry in "$@"; do
		url=${entry%% *}
		expected=${entry##* }
		tried+=("$url")

		if [[ -f $path ]]; then
			# A cached file counts for whichever candidate it matches.
			if printf '%s  %s\n' "$expected" "$path" | sha256sum --check --status; then
				printf '%s\n' "$path"
				return 0
			fi
			continue
		fi

		printf 'fetching %s\n  from %s\n' "$name" "$url" >&2
		if ! curl --fail --location --retry 2 --show-error "$url" --output "$path"; then
			# Unreachable or refused: no bytes to judge, so try the next host.
			rm -f "$path"
			printf '  unreachable, trying the next source\n' >&2
			continue
		fi

		if printf '%s  %s\n' "$expected" "$path" | sha256sum --check --status; then
			printf '%s\n' "$path"
			return 0
		fi

		# Reached the host, got a file, and it is not the pinned artifact.
		# Never silently fall through to another source: this is the case
		# the digest exists to catch.
		printf 'checksum mismatch: %s from %s\n' "$name" "$url" >&2
		printf '  expected %s\n  got      %s\n' \
			"$expected" "$(sha256sum "$path" | cut -d' ' -f1)" >&2
		rm -f "$path"
		exit 1
	done

	printf 'could not fetch %s from any pinned source:\n' "$name" >&2
	printf '  %s\n' "${tried[@]}" >&2
	exit 1
}

lib_archive=$(fetch_any "libpinyin-$LIBPINYIN_TAG.tar.gz" "${LIBPINYIN_SOURCES[@]}")
ibus_archive=$(fetch_any "ibus-libpinyin-$IBUS_LIBPINYIN_TAG.tar.gz" "${IBUS_LIBPINYIN_SOURCES[@]}")
read -r libpinyin_archive_sha256 _ < <(sha256sum "$lib_archive")
read -r ibus_libpinyin_archive_sha256 _ < <(sha256sum "$ibus_archive")

rm -rf "$work_dir/src/libpinyin-$LIBPINYIN_TAG" "$work_dir/src/ibus-libpinyin-$IBUS_LIBPINYIN_TAG"
tar -xzf "$lib_archive" -C "$work_dir/src"
tar -xzf "$ibus_archive" -C "$work_dir/src"

lib_src=$work_dir/src/libpinyin-$LIBPINYIN_TAG
ibus_src=$work_dir/src/ibus-libpinyin-$IBUS_LIBPINYIN_TAG

# The model data is the 18-file model20 export that build-oracle.sh drops into
# libpinyin's data dir (make install then ships it to $prefix/lib/libpinyin/data).
# Prefer a pre-extracted export from tools/model/fetch-model.sh when given, so a
# rebuild of the oracle does not re-download the archive. The SHA-256 was already
# verified against MODEL_SHA256 before that export was produced; applying it here
# changes WHERE the bytes come from, never WHETHER they are checked. With no
# --model-dir the pinned archive is downloaded and verified, exactly as before.
model_data_dir=$lib_src/data
mkdir -p "$model_data_dir"
if [[ -n $model_dir ]]; then
	model_dir=$(cd "$model_dir" && pwd)
	# Copy the validated inventory only: a stray extra file in the cache dir
	# must not ride into the pinned oracle's data dir, and a subdirectory
	# would abort cp outright. The 18 names were checked above, so nothing
	# here can be missing.
	for f in "${MODEL_FILES[@]}"; do
		cp "$model_dir/$f" "$model_data_dir/$f"
	done
	printf 'reusing pre-extracted model export from %s\n' "$model_dir" >&2
else
	model_archive=$(fetch model20.text.tar.gz "$MODEL_URL" "$MODEL_SHA256")
	tar -xzf "$model_archive" -C "$model_data_dir"
fi

patch_manifest=
if [[ -n $apply_patches_dir ]]; then
	if [[ ! -d $apply_patches_dir ]]; then
		printf '%s\n' "--apply-patches: not a directory: $apply_patches_dir" >&2
		exit 1
	fi
	apply_patches_dir=$(cd "$apply_patches_dir" && pwd)
	mapfile -t patches < <(find "$apply_patches_dir" -maxdepth 1 -type f -name '*.patch' -print | sort)
	if ((${#patches[@]} == 0)); then
		printf '%s\n' "--apply-patches: no *.patch files in $apply_patches_dir" >&2
		exit 1
	fi
	(
		cd "$lib_src"
		for p in "${patches[@]}"; do
			printf 'applying patch: %s\n' "$p" >&2
			patch -p1 --forward --no-backup-if-mismatch <"$p"
		done
	)
	patch_manifest=$prefix/oracle-patches.sha256
	(
		cd "$apply_patches_dir"
		# shellcheck disable=SC2016  # sha256sum wants literal names.
		find . -maxdepth 1 -type f -name '*.patch' -print0 | sort -z | xargs -0 sha256sum
	) >"$patch_manifest"
	read -r patch_manifest_sha256 _ < <(sha256sum "$patch_manifest")
	ORACLE_PIN_REF="$ORACLE_PIN_REF+patches-$patch_manifest_sha256"
fi

(
	cd "$lib_src"
	autoreconf --force --install --verbose
	./configure --prefix="$prefix" --disable-static --with-dbm=Tkrzw
	make -j"$jobs"
	make install
)

(
	cd "$ibus_src"
	autoreconf --force --install --verbose
	./configure --prefix="$prefix" \
		--disable-static \
		--disable-boost \
		--disable-cloud-input-mode \
		--disable-english-input-mode \
		--disable-libnotify \
		--disable-lua-extension
	make -j"$jobs"
)

shared_object=$(find "$prefix" -type f \( -name 'libpinyin.so' -o -name 'libpinyin.so.*' \) -print | sort | head -n 1)
[[ -n $shared_object ]] || {
	printf '%s\n' 'built libpinyin shared object not found' >&2
	exit 1
}

header=$prefix/include/libpinyin-$LIBPINYIN_TAG/pinyin.h
data_dir=$prefix/lib/libpinyin/data
data_manifest=$prefix/oracle-data.sha256
[[ -f $header && -d $data_dir ]] || {
	printf '%s\n' 'installed oracle header or data directory not found' >&2
	exit 1
}
(
	cd "$prefix"
	find lib/libpinyin/data -type f -print0 | sort -z | xargs -0 sha256sum
) >"$data_manifest"
read -r header_sha256 _ < <(sha256sum "$header")
read -r shared_object_sha256 _ < <(sha256sum "$shared_object")
read -r data_manifest_sha256 _ < <(sha256sum "$data_manifest")
{
	cat <<EOF
schema=pinyin-oracle-v1
pin_ref=$ORACLE_PIN_REF
libpinyin_tag=$LIBPINYIN_TAG
libpinyin_commit=$LIBPINYIN_SHA
ibus_libpinyin_tag=$IBUS_LIBPINYIN_TAG
ibus_libpinyin_commit=$IBUS_LIBPINYIN_SHA
# Which of the pinned archives this build actually fetched. The commits
# above identify the CODE and are what pin_ref keys on, so they -- and
# pin_ref with them -- are the same whichever archive was reachable; these
# two record which byte stream produced this prefix, so a rebuild elsewhere
# can be told apart from a re-download of the same file.
libpinyin_archive_sha256=$libpinyin_archive_sha256
ibus_libpinyin_archive_sha256=$ibus_libpinyin_archive_sha256
model_sha256=$MODEL_SHA256
dbm=Tkrzw
header_sha256=$header_sha256
shared_object_sha256=$shared_object_sha256
data_manifest_sha256=$data_manifest_sha256
EOF
	if [[ -n $patch_manifest ]]; then
		printf 'patches_manifest_sha256=%s\n' "$patch_manifest_sha256"
	fi
} >"$prefix/oracle-pin.txt"

printf 'libpinyin_tag=%s\nlibpinyin_commit=%s\n' "$LIBPINYIN_TAG" "$LIBPINYIN_SHA" >&2
printf 'ibus_libpinyin_tag=%s\nibus_libpinyin_commit=%s\n' "$IBUS_LIBPINYIN_TAG" "$IBUS_LIBPINYIN_SHA" >&2
printf '%s\n' "$shared_object"
