/*
 * fullpin-tables.h — pinned full-pinyin index tables for fullpin-diff.c.
 * Generated from libpinyin 2.11.91 (0c5e80e1) pinyin_parser_table.h
 * and the frozen HANYU inventory; keep in sync with
 * crates/oxpinyin-core/src/full_pinyin_index.rs.
 */
#ifndef FULLPIN_TABLES_H
#define FULLPIN_TABLES_H

/* Pinned luoma_pinyin_index (pinyin_parser_table.h:674):
 * (input spelling, canonical pinyin), 406 rows. */
static const struct index_row LUOMA_INDEX[] = {
    { "a", "a" },
    { "ai", "ai" },
    { "an", "an" },
    { "ang", "ang" },
    { "ao", "ao" },
    { "ba", "ba" },
    { "bai", "bai" },
    { "ban", "ban" },
    { "bang", "bang" },
    { "bao", "bao" },
    { "bei", "bei" },
    { "ben", "ben" },
    { "beng", "beng" },
    { "bi", "bi" },
    { "bian", "bian" },
    { "biao", "biao" },
    { "bieh", "bie" },
    { "bin", "bin" },
    { "bing", "bing" },
    { "bo", "bo" },
    { "bu", "bu" },
    { "cha", "cha" },
    { "chai", "chai" },
    { "chan", "chan" },
    { "chang", "chang" },
    { "chao", "chao" },
    { "che", "che" },
    { "chen", "chen" },
    { "cheng", "cheng" },
    { "chi", "qi" },
    { "chia", "qia" },
    { "chian", "qian" },
    { "chiang", "qiang" },
    { "chiao", "qiao" },
    { "chieh", "qie" },
    { "chih", "ch" },
    { "chin", "qin" },
    { "ching", "qing" },
    { "chiou", "qiu" },
    { "chong", "chong" },
    { "chou", "chou" },
    { "chu", "chu" },
    { "chuai", "chuai" },
    { "chuan", "chuan" },
    { "chuang", "chuang" },
    { "chuei", "chui" },
    { "chun", "chun" },
    { "chuo", "chuo" },
    { "chyong", "qiong" },
    { "chyu", "qu" },
    { "chyuan", "quan" },
    { "chyueh", "que" },
    { "chyun", "qun" },
    { "da", "da" },
    { "dai", "dai" },
    { "dan", "dan" },
    { "dang", "dang" },
    { "dao", "dao" },
    { "de", "de" },
    { "dei", "dei" },
    { "deng", "deng" },
    { "di", "di" },
    { "dian", "dian" },
    { "diao", "diao" },
    { "dieh", "die" },
    { "ding", "ding" },
    { "diou", "diu" },
    { "dong", "dong" },
    { "dou", "dou" },
    { "du", "du" },
    { "duan", "duan" },
    { "duei", "dui" },
    { "dun", "dun" },
    { "duo", "duo" },
    { "e", "e" },
    { "ei", "ei" },
    { "en", "en" },
    { "eng", "eng" },
    { "er", "er" },
    { "fa", "fa" },
    { "fan", "fan" },
    { "fang", "fang" },
    { "fei", "fei" },
    { "fen", "fen" },
    { "fo", "fo" },
    { "fou", "fou" },
    { "fu", "fu" },
    { "ga", "ga" },
    { "gai", "gai" },
    { "gan", "gan" },
    { "gang", "gang" },
    { "gao", "gao" },
    { "ge", "ge" },
    { "gei", "gei" },
    { "gen", "gen" },
    { "geng", "geng" },
    { "gong", "gong" },
    { "gou", "gou" },
    { "gu", "gu" },
    { "gua", "gua" },
    { "guai", "guai" },
    { "guan", "guan" },
    { "guang", "guang" },
    { "guei", "gui" },
    { "gun", "gun" },
    { "guo", "guo" },
    { "ha", "ha" },
    { "hai", "hai" },
    { "han", "han" },
    { "hang", "hang" },
    { "hao", "hao" },
    { "he", "he" },
    { "hei", "hei" },
    { "hen", "hen" },
    { "heng", "heng" },
    { "hong", "hong" },
    { "hou", "hou" },
    { "hu", "hu" },
    { "hua", "hua" },
    { "huai", "huai" },
    { "huan", "huan" },
    { "huang", "huang" },
    { "huei", "hui" },
    { "hun", "hun" },
    { "huo", "huo" },
    { "jha", "zha" },
    { "jhai", "zhai" },
    { "jhan", "zhan" },
    { "jhang", "zhang" },
    { "jhao", "zhao" },
    { "jhe", "zhe" },
    { "jhei", "zhei" },
    { "jhen", "zhen" },
    { "jheng", "zheng" },
    { "jhih", "zh" },
    { "jhong", "zhong" },
    { "jhou", "zhou" },
    { "jhu", "zhu" },
    { "jhua", "zhua" },
    { "jhuai", "zhuai" },
    { "jhuan", "zhuan" },
    { "jhuang", "zhuang" },
    { "jhuei", "zhui" },
    { "jhun", "zhun" },
    { "jhuo", "zhuo" },
    { "ji", "ji" },
    { "jia", "jia" },
    { "jian", "jian" },
    { "jiang", "jiang" },
    { "jiao", "jiao" },
    { "jieh", "jie" },
    { "jin", "jin" },
    { "jing", "jing" },
    { "jiou", "jiu" },
    { "jyong", "jiong" },
    { "jyu", "ju" },
    { "jyuan", "juan" },
    { "jyueh", "jue" },
    { "jyun", "jun" },
    { "ka", "ka" },
    { "kai", "kai" },
    { "kan", "kan" },
    { "kang", "kang" },
    { "kao", "kao" },
    { "ke", "ke" },
    { "ken", "ken" },
    { "keng", "keng" },
    { "kong", "kong" },
    { "kou", "kou" },
    { "ku", "ku" },
    { "kua", "kua" },
    { "kuai", "kuai" },
    { "kuan", "kuan" },
    { "kuang", "kuang" },
    { "kuei", "kui" },
    { "kun", "kun" },
    { "kuo", "kuo" },
    { "la", "la" },
    { "lai", "lai" },
    { "lan", "lan" },
    { "lang", "lang" },
    { "lao", "lao" },
    { "le", "le" },
    { "lei", "lei" },
    { "leng", "leng" },
    { "li", "li" },
    { "lia", "lia" },
    { "lian", "lian" },
    { "liang", "liang" },
    { "liao", "liao" },
    { "lieh", "lie" },
    { "lin", "lin" },
    { "ling", "ling" },
    { "liou", "liu" },
    { "lo", "lo" },
    { "long", "long" },
    { "lou", "lou" },
    { "lu", "lu" },
    { "luan", "luan" },
    { "lun", "lun" },
    { "luo", "luo" },
    { "lyu", "lv" },
    { "lyueh", "lve" },
    { "ma", "ma" },
    { "mai", "mai" },
    { "man", "man" },
    { "mang", "mang" },
    { "mao", "mao" },
    { "me", "me" },
    { "mei", "mei" },
    { "men", "men" },
    { "meng", "meng" },
    { "mi", "mi" },
    { "mian", "mian" },
    { "miao", "miao" },
    { "mieh", "mie" },
    { "min", "min" },
    { "ming", "ming" },
    { "miou", "miu" },
    { "mo", "mo" },
    { "mou", "mou" },
    { "mu", "mu" },
    { "na", "na" },
    { "nai", "nai" },
    { "nan", "nan" },
    { "nang", "nang" },
    { "nao", "nao" },
    { "ne", "ne" },
    { "nei", "nei" },
    { "nen", "nen" },
    { "neng", "neng" },
    { "ni", "ni" },
    { "nian", "nian" },
    { "niang", "niang" },
    { "niao", "niao" },
    { "nieh", "nie" },
    { "nin", "nin" },
    { "ning", "ning" },
    { "niou", "niu" },
    { "nong", "nong" },
    { "nou", "nou" },
    { "nu", "nu" },
    { "nuan", "nuan" },
    { "nun", "nun" },
    { "nuo", "nuo" },
    { "nyu", "nv" },
    { "nyueh", "nve" },
    { "o", "o" },
    { "ou", "ou" },
    { "pa", "pa" },
    { "pai", "pai" },
    { "pan", "pan" },
    { "pang", "pang" },
    { "pao", "pao" },
    { "pei", "pei" },
    { "pen", "pen" },
    { "peng", "peng" },
    { "pi", "pi" },
    { "pian", "pian" },
    { "piao", "piao" },
    { "pieh", "pie" },
    { "pin", "pin" },
    { "ping", "ping" },
    { "po", "po" },
    { "pou", "pou" },
    { "pu", "pu" },
    { "ran", "ran" },
    { "rang", "rang" },
    { "rao", "rao" },
    { "re", "re" },
    { "ren", "ren" },
    { "reng", "reng" },
    { "rih", "r" },
    { "rong", "rong" },
    { "rou", "rou" },
    { "ru", "ru" },
    { "ruan", "ruan" },
    { "ruei", "rui" },
    { "run", "run" },
    { "ruo", "ruo" },
    { "sa", "sa" },
    { "sai", "sai" },
    { "san", "san" },
    { "sang", "sang" },
    { "sao", "sao" },
    { "se", "se" },
    { "sen", "sen" },
    { "seng", "seng" },
    { "sha", "sha" },
    { "shai", "shai" },
    { "shan", "shan" },
    { "shang", "shang" },
    { "shao", "shao" },
    { "she", "she" },
    { "shei", "shei" },
    { "shen", "shen" },
    { "sheng", "sheng" },
    { "shih", "sh" },
    { "shou", "shou" },
    { "shu", "shu" },
    { "shua", "shua" },
    { "shuai", "shuai" },
    { "shuan", "shuan" },
    { "shuang", "shuang" },
    { "shuei", "shui" },
    { "shun", "shun" },
    { "shuo", "shuo" },
    { "si", "xi" },
    { "sia", "xia" },
    { "sian", "xian" },
    { "siang", "xiang" },
    { "siao", "xiao" },
    { "sieh", "xie" },
    { "sih", "s" },
    { "sin", "xin" },
    { "sing", "xing" },
    { "siou", "xiu" },
    { "song", "song" },
    { "sou", "sou" },
    { "su", "su" },
    { "suan", "suan" },
    { "suei", "sui" },
    { "sun", "sun" },
    { "suo", "suo" },
    { "syong", "xiong" },
    { "syu", "xu" },
    { "syuan", "xuan" },
    { "syueh", "xue" },
    { "syun", "xun" },
    { "ta", "ta" },
    { "tai", "tai" },
    { "tan", "tan" },
    { "tang", "tang" },
    { "tao", "tao" },
    { "te", "te" },
    { "teng", "teng" },
    { "ti", "ti" },
    { "tian", "tian" },
    { "tiao", "tiao" },
    { "tieh", "tie" },
    { "ting", "ting" },
    { "tong", "tong" },
    { "tou", "tou" },
    { "tsa", "ca" },
    { "tsai", "cai" },
    { "tsan", "can" },
    { "tsang", "cang" },
    { "tsao", "cao" },
    { "tse", "ce" },
    { "tsen", "cen" },
    { "tseng", "ceng" },
    { "tsih", "c" },
    { "tsong", "cong" },
    { "tsou", "cou" },
    { "tsu", "cu" },
    { "tsuan", "cuan" },
    { "tsuei", "cui" },
    { "tsun", "cun" },
    { "tsuo", "cuo" },
    { "tu", "tu" },
    { "tuan", "tuan" },
    { "tuei", "tui" },
    { "tun", "tun" },
    { "tuo", "tuo" },
    { "wa", "wa" },
    { "wai", "wai" },
    { "wan", "wan" },
    { "wang", "wang" },
    { "wei", "wei" },
    { "wo", "wo" },
    { "wong", "weng" },
    { "wu", "wu" },
    { "wun", "wen" },
    { "ya", "ya" },
    { "yai", "yai" },
    { "yan", "yan" },
    { "yang", "yang" },
    { "yao", "yao" },
    { "yeh", "ye" },
    { "yi", "yi" },
    { "yin", "yin" },
    { "ying", "ying" },
    { "yo", "yo" },
    { "yong", "yong" },
    { "you", "you" },
    { "yu", "yu" },
    { "yuan", "yuan" },
    { "yueh", "yue" },
    { "yun", "yun" },
    { "za", "za" },
    { "zai", "zai" },
    { "zan", "zan" },
    { "zang", "zang" },
    { "zao", "zao" },
    { "ze", "ze" },
    { "zei", "zei" },
    { "zen", "zen" },
    { "zeng", "zeng" },
    { "zih", "z" },
    { "zong", "zong" },
    { "zou", "zou" },
    { "zu", "zu" },
    { "zuan", "zuan" },
    { "zuei", "zui" },
    { "zun", "zun" },
    { "zuo", "zuo" },
};

/* Pinned secondary_zhuyin_index (pinyin_parser_table.h:1083):
 * (input spelling, canonical pinyin), 406 rows. */
static const struct index_row SECONDARY_INDEX[] = {
    { "a", "a" },
    { "ai", "ai" },
    { "an", "an" },
    { "ang", "ang" },
    { "au", "ao" },
    { "ba", "ba" },
    { "bai", "bai" },
    { "ban", "ban" },
    { "bang", "bang" },
    { "bau", "bao" },
    { "bei", "bei" },
    { "ben", "ben" },
    { "beng", "beng" },
    { "bi", "bi" },
    { "bian", "bian" },
    { "biau", "biao" },
    { "bie", "bie" },
    { "bin", "bin" },
    { "bing", "bing" },
    { "bo", "bo" },
    { "bu", "bu" },
    { "cha", "cha" },
    { "chai", "chai" },
    { "chan", "chan" },
    { "chang", "chang" },
    { "chau", "chao" },
    { "che", "che" },
    { "chen", "chen" },
    { "cheng", "cheng" },
    { "chi", "qi" },
    { "chia", "qia" },
    { "chian", "qian" },
    { "chiang", "qiang" },
    { "chiau", "qiao" },
    { "chie", "qie" },
    { "chin", "qin" },
    { "ching", "qing" },
    { "chiou", "qiu" },
    { "chiu", "qu" },
    { "chiuan", "quan" },
    { "chiue", "que" },
    { "chiun", "qun" },
    { "chiung", "qiong" },
    { "chou", "chou" },
    { "chr", "ch" },
    { "chu", "chu" },
    { "chuai", "chuai" },
    { "chuan", "chuan" },
    { "chuang", "chuang" },
    { "chuei", "chui" },
    { "chuen", "chun" },
    { "chung", "chong" },
    { "chuo", "chuo" },
    { "da", "da" },
    { "dai", "dai" },
    { "dan", "dan" },
    { "dang", "dang" },
    { "dau", "dao" },
    { "de", "de" },
    { "dei", "dei" },
    { "deng", "deng" },
    { "di", "di" },
    { "dian", "dian" },
    { "diau", "diao" },
    { "die", "die" },
    { "ding", "ding" },
    { "diou", "diu" },
    { "dou", "dou" },
    { "du", "du" },
    { "duan", "duan" },
    { "duei", "dui" },
    { "duen", "dun" },
    { "dung", "dong" },
    { "duo", "duo" },
    { "e", "e" },
    { "ei", "ei" },
    { "en", "en" },
    { "eng", "eng" },
    { "er", "er" },
    { "fa", "fa" },
    { "fan", "fan" },
    { "fang", "fang" },
    { "fei", "fei" },
    { "fen", "fen" },
    { "fo", "fo" },
    { "fou", "fou" },
    { "fu", "fu" },
    { "ga", "ga" },
    { "gai", "gai" },
    { "gan", "gan" },
    { "gang", "gang" },
    { "gau", "gao" },
    { "ge", "ge" },
    { "gei", "gei" },
    { "gen", "gen" },
    { "geng", "geng" },
    { "gou", "gou" },
    { "gu", "gu" },
    { "gua", "gua" },
    { "guai", "guai" },
    { "guan", "guan" },
    { "guang", "guang" },
    { "guei", "gui" },
    { "guen", "gun" },
    { "gung", "gong" },
    { "guo", "guo" },
    { "ha", "ha" },
    { "hai", "hai" },
    { "han", "han" },
    { "hang", "hang" },
    { "hau", "hao" },
    { "he", "he" },
    { "hei", "hei" },
    { "hen", "hen" },
    { "heng", "heng" },
    { "hou", "hou" },
    { "hu", "hu" },
    { "hua", "hua" },
    { "huai", "huai" },
    { "huan", "huan" },
    { "huang", "huang" },
    { "huei", "hui" },
    { "huen", "hun" },
    { "hung", "hong" },
    { "huo", "huo" },
    { "ja", "zha" },
    { "jai", "zhai" },
    { "jan", "zhan" },
    { "jang", "zhang" },
    { "jau", "zhao" },
    { "je", "zhe" },
    { "jei", "zhei" },
    { "jen", "zhen" },
    { "jeng", "zheng" },
    { "ji", "ji" },
    { "jia", "jia" },
    { "jian", "jian" },
    { "jiang", "jiang" },
    { "jiau", "jiao" },
    { "jie", "jie" },
    { "jin", "jin" },
    { "jing", "jing" },
    { "jiou", "jiu" },
    { "jiu", "ju" },
    { "jiuan", "juan" },
    { "jiue", "jue" },
    { "jiun", "jun" },
    { "jiung", "jiong" },
    { "jou", "zhou" },
    { "jr", "zh" },
    { "ju", "zhu" },
    { "jua", "zhua" },
    { "juai", "zhuai" },
    { "juan", "zhuan" },
    { "juang", "zhuang" },
    { "juei", "zhui" },
    { "juen", "zhun" },
    { "jung", "zhong" },
    { "juo", "zhuo" },
    { "ka", "ka" },
    { "kai", "kai" },
    { "kan", "kan" },
    { "kang", "kang" },
    { "kau", "kao" },
    { "ke", "ke" },
    { "ken", "ken" },
    { "keng", "keng" },
    { "kou", "kou" },
    { "ku", "ku" },
    { "kua", "kua" },
    { "kuai", "kuai" },
    { "kuan", "kuan" },
    { "kuang", "kuang" },
    { "kuei", "kui" },
    { "kuen", "kun" },
    { "kung", "kong" },
    { "kuo", "kuo" },
    { "la", "la" },
    { "lai", "lai" },
    { "lan", "lan" },
    { "lang", "lang" },
    { "lau", "lao" },
    { "le", "le" },
    { "lei", "lei" },
    { "leng", "leng" },
    { "li", "li" },
    { "lia", "lia" },
    { "lian", "lian" },
    { "liang", "liang" },
    { "liau", "liao" },
    { "lie", "lie" },
    { "lin", "lin" },
    { "ling", "ling" },
    { "liou", "liu" },
    { "liu", "lv" },
    { "liue", "lve" },
    { "lo", "lo" },
    { "lou", "lou" },
    { "lu", "lu" },
    { "luan", "luan" },
    { "luen", "lun" },
    { "lung", "long" },
    { "luo", "luo" },
    { "ma", "ma" },
    { "mai", "mai" },
    { "man", "man" },
    { "mang", "mang" },
    { "mau", "mao" },
    { "me", "me" },
    { "mei", "mei" },
    { "men", "men" },
    { "meng", "meng" },
    { "mi", "mi" },
    { "mian", "mian" },
    { "miau", "miao" },
    { "mie", "mie" },
    { "min", "min" },
    { "ming", "ming" },
    { "miou", "miu" },
    { "mo", "mo" },
    { "mou", "mou" },
    { "mu", "mu" },
    { "na", "na" },
    { "nai", "nai" },
    { "nan", "nan" },
    { "nang", "nang" },
    { "nau", "nao" },
    { "ne", "ne" },
    { "nei", "nei" },
    { "nen", "nen" },
    { "neng", "neng" },
    { "ni", "ni" },
    { "nian", "nian" },
    { "niang", "niang" },
    { "niau", "niao" },
    { "nie", "nie" },
    { "nin", "nin" },
    { "ning", "ning" },
    { "niou", "niu" },
    { "niu", "nv" },
    { "niue", "nve" },
    { "nou", "nou" },
    { "nu", "nu" },
    { "nuan", "nuan" },
    { "nuen", "nun" },
    { "nung", "nong" },
    { "nuo", "nuo" },
    { "o", "o" },
    { "ou", "ou" },
    { "pa", "pa" },
    { "pai", "pai" },
    { "pan", "pan" },
    { "pang", "pang" },
    { "pau", "pao" },
    { "pei", "pei" },
    { "pen", "pen" },
    { "peng", "peng" },
    { "pi", "pi" },
    { "pian", "pian" },
    { "piau", "piao" },
    { "pie", "pie" },
    { "pin", "pin" },
    { "ping", "ping" },
    { "po", "po" },
    { "pou", "pou" },
    { "pu", "pu" },
    { "r", "r" },
    { "ran", "ran" },
    { "rang", "rang" },
    { "rau", "rao" },
    { "re", "re" },
    { "ren", "ren" },
    { "reng", "reng" },
    { "rou", "rou" },
    { "ru", "ru" },
    { "ruan", "ruan" },
    { "ruei", "rui" },
    { "ruen", "run" },
    { "rung", "rong" },
    { "ruo", "ruo" },
    { "sa", "sa" },
    { "sai", "sai" },
    { "san", "san" },
    { "sang", "sang" },
    { "sau", "sao" },
    { "se", "se" },
    { "sen", "sen" },
    { "seng", "seng" },
    { "sha", "sha" },
    { "shai", "shai" },
    { "shan", "shan" },
    { "shang", "shang" },
    { "shau", "shao" },
    { "she", "she" },
    { "shei", "shei" },
    { "shen", "shen" },
    { "sheng", "sheng" },
    { "shi", "xi" },
    { "shia", "xia" },
    { "shian", "xian" },
    { "shiang", "xiang" },
    { "shiau", "xiao" },
    { "shie", "xie" },
    { "shin", "xin" },
    { "shing", "xing" },
    { "shiou", "xiu" },
    { "shiu", "xu" },
    { "shiuan", "xuan" },
    { "shiue", "xue" },
    { "shiun", "xun" },
    { "shiung", "xiong" },
    { "shou", "shou" },
    { "shr", "sh" },
    { "shu", "shu" },
    { "shua", "shua" },
    { "shuai", "shuai" },
    { "shuan", "shuan" },
    { "shuang", "shuang" },
    { "shuei", "shui" },
    { "shuen", "shun" },
    { "shuo", "shuo" },
    { "sou", "sou" },
    { "su", "su" },
    { "suan", "suan" },
    { "suei", "sui" },
    { "suen", "sun" },
    { "sung", "song" },
    { "suo", "suo" },
    { "sz", "s" },
    { "ta", "ta" },
    { "tai", "tai" },
    { "tan", "tan" },
    { "tang", "tang" },
    { "tau", "tao" },
    { "te", "te" },
    { "teng", "teng" },
    { "ti", "ti" },
    { "tian", "tian" },
    { "tiau", "tiao" },
    { "tie", "tie" },
    { "ting", "ting" },
    { "tou", "tou" },
    { "tsa", "ca" },
    { "tsai", "cai" },
    { "tsan", "can" },
    { "tsang", "cang" },
    { "tsau", "cao" },
    { "tse", "ce" },
    { "tsen", "cen" },
    { "tseng", "ceng" },
    { "tsou", "cou" },
    { "tsu", "cu" },
    { "tsuan", "cuan" },
    { "tsuei", "cui" },
    { "tsun", "cun" },
    { "tsung", "cong" },
    { "tsuo", "cuo" },
    { "tsz", "c" },
    { "tu", "tu" },
    { "tuan", "tuan" },
    { "tuei", "tui" },
    { "tuen", "tun" },
    { "tung", "tong" },
    { "tuo", "tuo" },
    { "tz", "z" },
    { "tza", "za" },
    { "tzai", "zai" },
    { "tzan", "zan" },
    { "tzang", "zang" },
    { "tzau", "zao" },
    { "tze", "ze" },
    { "tzei", "zei" },
    { "tzen", "zen" },
    { "tzeng", "zeng" },
    { "tzou", "zou" },
    { "tzu", "zu" },
    { "tzuan", "zuan" },
    { "tzuei", "zui" },
    { "tzuen", "zun" },
    { "tzung", "zong" },
    { "tzuo", "zuo" },
    { "wa", "wa" },
    { "wai", "wai" },
    { "wan", "wan" },
    { "wang", "wang" },
    { "wei", "wei" },
    { "wen", "wen" },
    { "weng", "weng" },
    { "wo", "wo" },
    { "wu", "wu" },
    { "ya", "ya" },
    { "yai", "yai" },
    { "yan", "yan" },
    { "yang", "yang" },
    { "yau", "yao" },
    { "ye", "ye" },
    { "yi", "yi" },
    { "yin", "yin" },
    { "ying", "ying" },
    { "yo", "yo" },
    { "you", "you" },
    { "yu", "yu" },
    { "yuan", "yuan" },
    { "yue", "yue" },
    { "yun", "yun" },
    { "yung", "yong" },
};

/* The frozen HANYU inventory (405 complete syllables) for the
 * scheme-1 re-sweep. */
static const char *const HANYU_SYLLABLES[] = {
    "a",
    "ai",
    "an",
    "ang",
    "ao",
    "ba",
    "bai",
    "ban",
    "bang",
    "bao",
    "bei",
    "ben",
    "beng",
    "bi",
    "bian",
    "biao",
    "bie",
    "bin",
    "bing",
    "bo",
    "bu",
    "ca",
    "cai",
    "can",
    "cang",
    "cao",
    "ce",
    "cen",
    "ceng",
    "ci",
    "cong",
    "cou",
    "cu",
    "cuan",
    "cui",
    "cun",
    "cuo",
    "cha",
    "chai",
    "chan",
    "chang",
    "chao",
    "che",
    "chen",
    "cheng",
    "chi",
    "chong",
    "chou",
    "chu",
    "chuai",
    "chuan",
    "chuang",
    "chui",
    "chun",
    "chuo",
    "da",
    "dai",
    "dan",
    "dang",
    "dao",
    "de",
    "dei",
    "deng",
    "di",
    "dia",
    "dian",
    "diao",
    "die",
    "ding",
    "diu",
    "dong",
    "dou",
    "du",
    "duan",
    "dui",
    "dun",
    "duo",
    "e",
    "ei",
    "en",
    "er",
    "fa",
    "fan",
    "fang",
    "fei",
    "fen",
    "feng",
    "fo",
    "fou",
    "fu",
    "ga",
    "gai",
    "gan",
    "gang",
    "gao",
    "ge",
    "gei",
    "gen",
    "geng",
    "gong",
    "gou",
    "gu",
    "gua",
    "guai",
    "guan",
    "guang",
    "gui",
    "gun",
    "guo",
    "ha",
    "hai",
    "han",
    "hang",
    "hao",
    "he",
    "hei",
    "hen",
    "heng",
    "hong",
    "hou",
    "hu",
    "hua",
    "huai",
    "huan",
    "huang",
    "hui",
    "hun",
    "huo",
    "ji",
    "jia",
    "jian",
    "jiang",
    "jiao",
    "jie",
    "jin",
    "jing",
    "jiong",
    "jiu",
    "ju",
    "juan",
    "jue",
    "jun",
    "ka",
    "kai",
    "kan",
    "kang",
    "kao",
    "ke",
    "ken",
    "keng",
    "kong",
    "kou",
    "ku",
    "kua",
    "kuai",
    "kuan",
    "kuang",
    "kui",
    "kun",
    "kuo",
    "la",
    "lai",
    "lan",
    "lang",
    "lao",
    "le",
    "lei",
    "leng",
    "li",
    "lia",
    "lian",
    "liang",
    "liao",
    "lie",
    "lin",
    "ling",
    "liu",
    "lo",
    "long",
    "lou",
    "lu",
    "luan",
    "lun",
    "luo",
    "lv",
    "lve",
    "ma",
    "mai",
    "man",
    "mang",
    "mao",
    "me",
    "mei",
    "men",
    "meng",
    "mi",
    "mian",
    "miao",
    "mie",
    "min",
    "ming",
    "miu",
    "mo",
    "mou",
    "mu",
    "na",
    "nai",
    "nan",
    "nang",
    "nao",
    "ne",
    "nei",
    "nen",
    "neng",
    "ni",
    "nian",
    "niang",
    "niao",
    "nie",
    "nin",
    "ning",
    "niu",
    "ng",
    "nong",
    "nou",
    "nu",
    "nuan",
    "nuo",
    "nv",
    "nve",
    "o",
    "ou",
    "pa",
    "pai",
    "pan",
    "pang",
    "pao",
    "pei",
    "pen",
    "peng",
    "pi",
    "pian",
    "piao",
    "pie",
    "pin",
    "ping",
    "po",
    "pou",
    "pu",
    "qi",
    "qia",
    "qian",
    "qiang",
    "qiao",
    "qie",
    "qin",
    "qing",
    "qiong",
    "qiu",
    "qu",
    "quan",
    "que",
    "qun",
    "ran",
    "rang",
    "rao",
    "re",
    "ren",
    "reng",
    "ri",
    "rong",
    "rou",
    "ru",
    "ruan",
    "rui",
    "run",
    "ruo",
    "sa",
    "sai",
    "san",
    "sang",
    "sao",
    "se",
    "sen",
    "seng",
    "si",
    "song",
    "sou",
    "su",
    "suan",
    "sui",
    "sun",
    "suo",
    "sha",
    "shai",
    "shan",
    "shang",
    "shao",
    "she",
    "shei",
    "shen",
    "sheng",
    "shi",
    "shou",
    "shu",
    "shua",
    "shuai",
    "shuan",
    "shuang",
    "shui",
    "shun",
    "shuo",
    "ta",
    "tai",
    "tan",
    "tang",
    "tao",
    "te",
    "teng",
    "ti",
    "tian",
    "tiao",
    "tie",
    "ting",
    "tong",
    "tou",
    "tu",
    "tuan",
    "tui",
    "tun",
    "tuo",
    "wa",
    "wai",
    "wan",
    "wang",
    "wei",
    "wen",
    "weng",
    "wo",
    "wu",
    "xi",
    "xia",
    "xian",
    "xiang",
    "xiao",
    "xie",
    "xin",
    "xing",
    "xiong",
    "xiu",
    "xu",
    "xuan",
    "xue",
    "xun",
    "ya",
    "yan",
    "yang",
    "yao",
    "ye",
    "yi",
    "yin",
    "ying",
    "yo",
    "yong",
    "you",
    "yu",
    "yuan",
    "yue",
    "yun",
    "za",
    "zai",
    "zan",
    "zang",
    "zao",
    "ze",
    "zei",
    "zen",
    "zeng",
    "zi",
    "zong",
    "zou",
    "zu",
    "zuan",
    "zui",
    "zun",
    "zuo",
    "zha",
    "zhai",
    "zhan",
    "zhang",
    "zhao",
    "zhe",
    "zhen",
    "zheng",
    "zhi",
    "zhong",
    "zhou",
    "zhu",
    "zhua",
    "zhuai",
    "zhuan",
    "zhuang",
    "zhui",
    "zhun",
    "zhuo",
};

#endif /* FULLPIN_TABLES_H */
