//! CLI-level contract for the `oxpinyin-dictool` binary — G2 of the
//! testing-strategy assessment (`testing-strategy.md` §2): the crate
//! had unit tests over import/export internals but no black-box test
//! over the shipped command line.
//!
//! The round-trip law is a **fixed point** rather than a hand-written
//! golden file: `import → export` produces the canonical interchange
//! text (the golden, generated by the pinned ABI path itself), and
//! re-importing that text and exporting again must reproduce it
//! byte-for-byte. That is exactly the property the Import/Export
//! buttons of the frontend rely on — export what you imported, and the
//! second cycle changes nothing — and it catches the classic
//! round-trip bug class (count drift, pinyin re-canonicalization,
//! row-order instability) without freezing bytes no human has verified.
//!
//! The corpus lives here rather than under `fixtures/`: the w3 tree is
//! DBM binaries under a checksum manifest and w4 is oracle-capture
//! territory with a provenance check, and neither wants a new text file
//! that is neither of those things.
//!
//! Linux-only like the rest of the C-ABI surface (`oxpinyin-capi`
//! drags glib); the workspace's macOS/Windows lanes exclude this crate,
//! so this file runs in the Linux test and store-backend lanes.

use std::path::PathBuf;
use std::process::Command;

/// The classic-format corpus: comments, blanks, a 2-field line (ABI
/// default count), and 3-field lines with explicit counts.
const INPUT: &str = "\
# dictool CLI round-trip corpus

你好 ni'hao 5
世界 shi'jie
试试 shi'shi 2
计算机 ji'suan'ji 10
";

fn temp_dir(tag: &str) -> PathBuf {
    let path =
        std::env::temp_dir().join(format!("oxpinyin-dictool-cli-{tag}-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&path);
    path
}

fn dictool(args: &[&str]) -> std::process::Output {
    Command::new(env!("CARGO_BIN_EXE_oxpinyin-dictool"))
        .args(args)
        .output()
        .expect("the dictool binary spawns")
}

fn run(args: &[&str]) -> (bool, String) {
    let output = dictool(args);
    let stderr = String::from_utf8_lossy(&output.stderr).into_owned();
    (output.status.success(), stderr)
}

/// `--help` succeeds and prints the usage block.
#[test]
fn help_exits_zero_and_prints_usage() {
    let output = dictool(&["--help"]);
    assert!(output.status.success(), "--help must exit 0");
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("Usage:"), "usage goes to stdout: {stdout}");
    assert!(stdout.contains("import"), "the import subcommand is named");
    assert!(stdout.contains("export"), "the export subcommand is named");
}

/// The golden round-trip: the first export is the canonical text, and a
/// second import/export cycle reproduces it exactly.
#[test]
fn import_then_export_is_a_fixed_point() {
    let work = temp_dir("roundtrip");
    let user_a = work.join("user-a");
    let user_b = work.join("user-b");
    std::fs::create_dir_all(&user_a).expect("user dir A creates");
    std::fs::create_dir_all(&user_b).expect("user dir B creates");
    let input = work.join("input.txt");
    std::fs::write(&input, INPUT).expect("corpus writes");
    let first_export = work.join("export-1.txt");
    let second_export = work.join("export-2.txt");

    let (ok, stderr) = run(&[
        "import",
        "--user-dir",
        user_a.to_str().expect("temp path is UTF-8"),
        input.to_str().expect("temp path is UTF-8"),
    ]);
    assert!(ok, "import must succeed: {stderr}");

    let (ok, stderr) = run(&[
        "export",
        "--user-dir",
        user_a.to_str().expect("temp path is UTF-8"),
        first_export.to_str().expect("temp path is UTF-8"),
    ]);
    assert!(ok, "first export must succeed: {stderr}");

    // The golden shape: every row is the 3-field form with a numeric
    // count (comments and blanks are dictool's parse-time superset and
    // never reappear), and every imported phrase survived.
    let golden = std::fs::read_to_string(&first_export).expect("export reads");
    let mut phrases = Vec::new();
    for line in golden.lines() {
        let fields: Vec<&str> = line.split([' ', '\t']).filter(|f| !f.is_empty()).collect();
        assert_eq!(
            fields.len(),
            3,
            "an exported row is `phrase pinyin count`: {line:?}"
        );
        assert!(
            fields[2].parse::<u64>().is_ok(),
            "the count is numeric: {line:?}"
        );
        phrases.push(fields[0].to_owned());
    }
    for phrase in ["你好", "世界", "试试", "计算机"] {
        assert!(
            phrases.contains(&phrase.to_owned()),
            "phrase {phrase} must survive the import"
        );
    }

    // The fixed point: import the golden text into a fresh store,
    // export, and demand byte equality.
    let (ok, stderr) = run(&[
        "import",
        "--user-dir",
        user_b.to_str().expect("temp path is UTF-8"),
        first_export.to_str().expect("temp path is UTF-8"),
    ]);
    assert!(ok, "re-import must succeed: {stderr}");
    let (ok, stderr) = run(&[
        "export",
        "--user-dir",
        user_b.to_str().expect("temp path is UTF-8"),
        second_export.to_str().expect("temp path is UTF-8"),
    ]);
    assert!(ok, "second export must succeed: {stderr}");
    assert_eq!(
        std::fs::read(&first_export).expect("golden reads"),
        std::fs::read(&second_export).expect("second export reads"),
        "import→export must be a fixed point: count drift, pinyin \
         re-canonicalization, or row-order instability all fail this"
    );

    std::fs::remove_dir_all(&work).ok();
}

/// A malformed input line fails the run with the line-numbered message
/// on stderr and a non-zero exit; a missing input file is a failure
/// too, not a crash.
#[test]
fn malformed_input_fails_with_a_line_numbered_error() {
    let work = temp_dir("malformed");
    let user = work.join("user");
    std::fs::create_dir_all(&user).expect("user dir creates");
    let user_flag = user.to_str().expect("temp path is UTF-8").to_owned();

    let bad = work.join("bad.txt");
    std::fs::write(&bad, "你好 ni'hao 5\njustonefield\n").expect("corpus writes");
    let (ok, stderr) = run(&[
        "import",
        "--user-dir",
        &user_flag,
        bad.to_str().expect("temp path is UTF-8"),
    ]);
    assert!(!ok, "a malformed line must fail the run");
    assert!(
        stderr.contains("oxpinyin-dictool:"),
        "the error is prefixed by the tool name: {stderr}"
    );
    assert!(
        stderr.contains("line 2:"),
        "the 1-based line number is reported: {stderr}"
    );

    let missing = work.join("absent.txt");
    let (ok, stderr) = run(&[
        "import",
        "--user-dir",
        &user_flag,
        missing.to_str().expect("temp path is UTF-8"),
    ]);
    assert!(!ok, "a missing input file must fail the run");
    assert!(
        stderr.contains("oxpinyin-dictool:"),
        "still the typed failure shape: {stderr}"
    );

    // Missing the file argument entirely is the usage failure.
    let (ok, stderr) = run(&["import", "--user-dir", &user_flag]);
    assert!(!ok, "import without a file must fail");
    assert!(
        stderr.contains("import requires an input"),
        "the usage message names the missing argument: {stderr}"
    );

    std::fs::remove_dir_all(&work).ok();
}

/// Export from a user dir that never saw an import answers an empty
/// document (or a bare header-free empty file), not an error.
#[test]
fn export_of_a_fresh_user_dir_is_clean() {
    let work = temp_dir("fresh-export");
    let user = work.join("user");
    std::fs::create_dir_all(&user).expect("user dir creates");
    let out = work.join("export.txt");
    let (ok, stderr) = run(&[
        "export",
        "--user-dir",
        user.to_str().expect("temp path is UTF-8"),
        out.to_str().expect("temp path is UTF-8"),
    ]);
    assert!(ok, "export from a fresh user dir must succeed: {stderr}");
    let body = std::fs::read_to_string(&out).expect("export reads");
    assert!(
        body.lines().all(str::is_empty),
        "no phrase rows can exist yet: {body:?}"
    );
    std::fs::remove_dir_all(&work).ok();
}
