//! The cxx bridge to `shim.cc` — the crate's only FFI surface.
//!
//! `#[cxx::bridge]` expands to `unsafe extern "C"` declarations and the
//! `unsafe` blocks that call them, which the workspace's
//! `unsafe_code = "deny"` would otherwise reject. The allow is scoped to
//! this module and nothing else: every declaration below is generated by
//! cxx from the signatures in `shim.h`, and cxx is what checks that the
//! two sides agree — a mismatch is a C++ compile error, not a runtime
//! one. No hand-written `unsafe` appears here or anywhere else in the
//! tkrzw backend.
//!
//! # Safety
//!
//! Two invariants are the caller's to keep, and `super` keeps both:
//!
//! - An `Iter` borrows the `Db` it was made from. cxx cannot express
//!   that lifetime across `UniquePtr`, so every iterator in `super` is a
//!   local of the method that made it, dropped before the store is.
//! - `db_apply`, `db_synchronize` and `db_rebuild` mutate through a
//!   shared reference. That is sound because tkrzw documents every
//!   TreeDBM operation as thread-safe — the database does its own
//!   locking — which is also what lets the backend keep `get` and
//!   `write` on `&self` like its redb and LMDB peers.
#![allow(unsafe_code)]

#[cxx::bridge(namespace = "oxpinyin_tkrzw")]
pub(crate) mod ffi {
    /// One tkrzw `Status`: its code and its message.
    ///
    /// The codes are `tkrzw::Status::Code`; only `SUCCESS` and
    /// `SYSTEM_ERROR` are named on the Rust side, and everything else is
    /// reported verbatim.
    struct ShimStatus {
        code: i32,
        message: String,
    }

    /// One buffered write, applied as part of a `ProcessMulti` batch.
    ///
    /// `remove` picks between writing `value` and deleting the record;
    /// `value` is ignored when `remove` is set.
    struct Mutation {
        key: Vec<u8>,
        value: Vec<u8>,
        remove: bool,
    }

    unsafe extern "C++" {
        include!("oxpinyin-store/src/tkrzw/shim.h");

        /// An open TreeDBM, closed when the handle drops.
        type Db;
        /// A cursor over an open [`Db`].
        type Iter;

        fn open_db(
            path: &[u8],
            writable: bool,
            no_create: bool,
            status: &mut ShimStatus,
        ) -> UniquePtr<Db>;

        fn db_get(db: &Db, key: &[u8], value: &mut Vec<u8>, found: &mut bool) -> ShimStatus;

        fn db_apply(db: &Db, mutations: &[Mutation]) -> ShimStatus;

        fn db_synchronize(db: &Db, hard: bool) -> ShimStatus;

        fn db_rebuild(db: &Db) -> ShimStatus;

        fn db_iter(db: &Db) -> UniquePtr<Iter>;

        fn iter_jump(iter: Pin<&mut Iter>, key: &[u8]) -> ShimStatus;

        fn iter_get(
            iter: Pin<&mut Iter>,
            key: &mut Vec<u8>,
            value: &mut Vec<u8>,
            found: &mut bool,
        ) -> ShimStatus;

        fn iter_next(iter: Pin<&mut Iter>) -> ShimStatus;
    }
}
