//! Build script: generates phf maps over the frozen syllable inventories.
//!
//! `src/syllables.rs` stays the single source of truth. This script extracts
//! the four `pub static … [&str; N]` tables' string entries and emits
//! `phf::Map<&'static str, u16>` statics (spelling → tier index) into
//! `OUT_DIR`; `src/syllables.rs` includes them. Generation is deterministic —
//! the same inventory produces byte-identical output — and fails the build
//! loudly if a table goes missing, changes shape, or repeats a spelling.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

/// `(source table, generated map)` pairs, in tier order: the order
/// `SyllableKey::from_text` / `from_canonical_text` consult them.
const TABLES: &[(&str, &str)] = &[
    ("FULL_PINYIN_SYLLABLES", "FULL_PINYIN_SYLLABLE_MAP"),
    ("INCOMPLETE_PINYIN_KEYS", "INCOMPLETE_PINYIN_KEY_MAP"),
    (
        "OPTION_ONLY_COMPLETE_SYLLABLES",
        "OPTION_ONLY_COMPLETE_SYLLABLE_MAP",
    ),
    (
        "ZHUYIN_ONLY_COMPLETE_SYLLABLES",
        "ZHUYIN_ONLY_COMPLETE_SYLLABLE_MAP",
    ),
];

fn main() {
    println!("cargo:rerun-if-changed=src/syllables.rs");
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set by cargo"));
    let source = fs::read_to_string("src/syllables.rs").expect("read src/syllables.rs");

    let mut generated =
        String::from("// Generated by build.rs from src/syllables.rs; do not edit.\n\n");
    for (table, map) in TABLES {
        let (declared, entries) = extract(&source, table)
            .unwrap_or_else(|| panic!("{table}: table not found in src/syllables.rs"));
        assert_eq!(
            entries.len(),
            declared,
            "{table}: declared [&str; {declared}] but found {} entries",
            entries.len()
        );
        let mut phf = phf_codegen::Map::new();
        for (index, entry) in entries.iter().enumerate() {
            // Codegen applies its own `{:?}` quoting to the key (`FmtConst`),
            // so the raw spelling goes in — debugging it here would
            // double-escape every entry.
            phf.entry(entry.clone(), &index.to_string());
        }
        writeln!(
            generated,
            "pub(crate) static {map}: ::phf::Map<&'static str, u16> = {};",
            phf.build()
        )
        .expect("write generated map");
        writeln!(generated).expect("write generated map separator");
    }

    fs::write(out_dir.join("syllable_maps.rs"), generated).expect("write syllable_maps.rs");
}

/// Extracts a frozen `pub static NAME: [&str; COUNT] = ["…", …];` table from
/// the syllable source, resolving `COUNT` through its
/// `pub const COUNT: usize = …;` definition: the declared length and the
/// string entries.
fn extract(source: &str, name: &str) -> Option<(usize, Vec<String>)> {
    let marker = format!("static {name}: [&str;");
    let table = source.find(&marker)?;
    let length_start = table + marker.len();
    let length_end = source[length_start..].find(']')? + length_start;
    let count_ident = source[length_start..length_end].trim();

    let count_marker = format!("const {count_ident}: usize = ");
    let count_start = source.find(&count_marker)? + count_marker.len();
    let count_end = source[count_start..].find(';')? + count_start;
    let declared = source[count_start..count_end].trim().parse().ok()?;

    // The assignment may wrap (`= \n    [`): find the `=` closing the
    // declaration, then the opening bracket after it.
    let eq = source[length_end..]
        .find('=')
        .unwrap_or_else(|| panic!("{name}: no array assignment found"))
        + length_end;
    let open = source[eq..]
        .find('[')
        .unwrap_or_else(|| panic!("{name}: no array body found"))
        + eq
        + 1;
    let close = source[open..]
        .find("];")
        .unwrap_or_else(|| panic!("{name}: unterminated array body"))
        + open;
    let body = &source[open..close];

    // The body holds only comma-separated string literals; the entries are
    // the quoted pieces.
    let mut pieces = body.split('"');
    pieces.next();
    let mut entries = Vec::new();
    while let Some(entry) = pieces.next() {
        entries.push(entry.to_owned());
        pieces.next();
    }
    Some((declared, entries))
}
