#!/usr/bin/env bash
# release-rpm.sh — split a staged drop-in tree into Fedora runtime/devel RPMs
# in the shape of the real libpinyin packaging:
#
#   oxpinyin-libpinyin-<backend>        ~ libpinyin + libzhuyin
#   oxpinyin-libpinyin-<backend>-devel  ~ libpinyin-devel + libzhuyin-devel
#
# Installing the runtime RPM takes over from the distro's libpinyin/libzhuyin
# in their entirety: rpm's dependency generator emits the soname Provides the
# real packages carry (libpinyin.so.15()(64bit), libzhuyin.so.15()(64bit)),
# Obsoletes swaps the installed packages out, and Provides: libpinyin =
# 2.11.91 / libzhuyin = 2.11.91 keeps every "Requires: libpinyin >= …"
# consumer resolving. libpinyin-data is deliberately not obsoleted: it is a
# separate package on Fedora and the library reads it in place.
#
# Obsoletes (not Conflicts) is the takeover mechanism: a package may not
# Conflict with a name it also Provides — rpm treats that as a self-conflict.
#
# The staged tree is shipped as Source0 and only copied in %install; the RPM
# rebuilds nothing. Requires on the backend/glib libraries are generated by
# rpm's ELF scanner from DT_NEEDED (kyotocabinet-libs, glib2, glibc, libgcc),
# matching how the real libpinyin carries them.
#
# Usage: release-rpm.sh <backend> <version> <stage-root> <outdir>
#   e.g. release-rpm.sh kyotocabinet 0.1.0 stage dist

set -euo pipefail

BACKEND="${1:?backend required}"
VERSION="${2:?version required}"
STAGE="${3:?stage root required}"
OUTDIR="${4:?outdir required}"

# Mirror [package.metadata.capi.pkg_config].version: the libpinyin release
# whose ABI and consumers this drop-in answers to.
PCVER="2.11.91"
NAME="oxpinyin-libpinyin-${BACKEND}"

[ -d "$STAGE/usr" ] || { echo "error: $STAGE/usr missing" >&2; exit 1; }
mkdir -p -- "$OUTDIR"

WORK="$(mktemp -d)"
trap 'rm -rf -- "$WORK"' EXIT
mkdir -p -- "$WORK"/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
TOPDIR="$(cd -- "$WORK" && pwd)"

tar -czf "$WORK/SOURCES/staged-tree.tar.gz" -C "$STAGE" usr

cat > "$WORK/SPECS/${NAME}.spec" <<EOF
%define debug_package %{nil}
Name:           $NAME
Version:        $VERSION
Release:        1%{?dist}
Summary:        Library to deal with pinyin — oxpinyin drop-in, $BACKEND store
License:        GPL-3.0-or-later
URL:            https://github.com/shenghaoc/oxpinyin
Source0:        staged-tree.tar.gz
Obsoletes:      libpinyin libzhuyin
Provides:       libpinyin = $PCVER libzhuyin = $PCVER

%description
oxpinyin is a portable Rust re-expression of libpinyin. This package installs
libpinyin.so.15 and libzhuyin.so.15 built against the $BACKEND store backend,
replacing libpinyin and libzhuyin in their entirety. It carries no data of its
own: the model files remain those of the installed libpinyin-data package.

%package devel
Summary:        Development files for oxpinyin ($BACKEND store)
License:        GPL-3.0-or-later
Requires:       %{name} = %{version}-%{release}
Obsoletes:      libpinyin-devel libzhuyin-devel
Provides:       libpinyin-devel = $PCVER libzhuyin-devel = $PCVER

%description devel
Headers, pkg-config files, linker symlinks and static archives for the
oxpinyin drop-in libpinyin.so.15 / libzhuyin.so.15.

%prep
%setup -q -c -n stage

%build
# The staged tree is prebuilt; nothing to compile.

%install
mkdir -p %{buildroot}
# %setup -c unpacks INSIDE stage/, which is also the build subdirectory
# %install runs from — copy from the explicit builddir path, not "stage/usr".
cp -a %{_builddir}/stage/usr %{buildroot}/

%files
%{_libdir}/libpinyin.so.15*
%{_libdir}/libzhuyin.so.15*

%files devel
%{_includedir}/libpinyin-2.11.91/
%{_libdir}/libpinyin.so
%{_libdir}/libzhuyin.so
%{_libdir}/libpinyin.a
%{_libdir}/libzhuyin.a
%{_libdir}/pkgconfig/libpinyin.pc
%{_libdir}/pkgconfig/libzhuyin.pc

%changelog
* Sat Sep 06 2026 Shenghao Chen <shenghaoc@outlook.com> - $VERSION-1
- Release build of the oxpinyin drop-in ($BACKEND store backend);
  replaces libpinyin/libzhuyin in their entirety.
EOF

rpmbuild --define "_topdir $TOPDIR" -bb "$WORK/SPECS/${NAME}.spec"

# Collect every produced RPM (there may be vendor-suffixed names) and verify
# each one's payload is complete before it leaves the script.
shopt -s nullglob
rpms=("$TOPDIR"/RPMS/*/*.rpm)
shopt -u nullglob
[ "${#rpms[@]}" -gt 0 ] || { echo "error: rpmbuild produced no RPMs" >&2; exit 1; }
for rpm in "${rpms[@]}"; do
  rpm -qlp "$rpm" >/dev/null
  cp -f -- "$rpm" "$OUTDIR/"
done

echo "== rpms written to $OUTDIR =="
ls -l "$OUTDIR"
